"""initial_schema

Revision ID: b27df8dbee4b
Revises: 
Create Date: 2026-02-03 19:59:27.821794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY, TSVECTOR

# revision identifiers, used by Alembic.
revision: str = 'b27df8dbee4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_nconst', sa.String(length=20), nullable=False),
    sa.Column('primary_name', sa.String(length=300), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_people_id'), 'catalog_people', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_people_imdb_nconst'), 'catalog_people', ['imdb_nconst'], unique=True)
    op.create_table('catalog_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imdb_tconst', sa.String(length=20), nullable=False),
    sa.Column('title_type', sa.String(length=50), nullable=True),
    sa.Column('primary_title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=200), nullable=True),
    sa.Column('title_search_text', sa.Text(), nullable=True),
    sa.Column('ts_vector', TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_titles_genres', 'catalog_titles', ['genres'], unique=False)
    op.create_index(op.f('ix_catalog_titles_id'), 'catalog_titles', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_titles_imdb_tconst'), 'catalog_titles', ['imdb_tconst'], unique=True)
    op.create_index('ix_catalog_titles_start_year', 'catalog_titles', ['start_year'], unique=False)
    op.create_index('ix_catalog_titles_ts_vector', 'catalog_titles', ['ts_vector'], unique=False, postgresql_using='gin')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('catalog_akas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('localized_title', sa.String(length=1000), nullable=True),
    sa.Column('region', sa.String(length=10), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_original', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['catalog_titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_akas_id'), 'catalog_akas', ['id'], unique=False)
    op.create_index('ix_catalog_akas_title_id', 'catalog_akas', ['title_id'], unique=False)
    op.create_table('catalog_crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('director_nconsts', ARRAY(sa.String()), nullable=True),
    sa.Column('writer_nconsts', ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['catalog_titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id')
    )
    op.create_index(op.f('ix_catalog_crew_id'), 'catalog_crew', ['id'], unique=False)
    op.create_table('catalog_principals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('job', sa.Text(), nullable=True),
    sa.Column('characters', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['catalog_people.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['catalog_titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_principals_id'), 'catalog_principals', ['id'], unique=False)
    op.create_index('ix_catalog_principals_person_id', 'catalog_principals', ['person_id'], unique=False)
    op.create_index('ix_catalog_principals_title_id', 'catalog_principals', ['title_id'], unique=False)
    op.create_table('catalog_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('num_votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['catalog_titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_id')
    )
    op.create_index(op.f('ix_catalog_ratings_id'), 'catalog_ratings', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_catalog_ratings_id'), table_name='catalog_ratings')
    op.drop_table('catalog_ratings')
    op.drop_index('ix_catalog_principals_title_id', table_name='catalog_principals')
    op.drop_index('ix_catalog_principals_person_id', table_name='catalog_principals')
    op.drop_index(op.f('ix_catalog_principals_id'), table_name='catalog_principals')
    op.drop_table('catalog_principals')
    op.drop_index(op.f('ix_catalog_crew_id'), table_name='catalog_crew')
    op.drop_table('catalog_crew')
    op.drop_index('ix_catalog_akas_title_id', table_name='catalog_akas')
    op.drop_index(op.f('ix_catalog_akas_id'), table_name='catalog_akas')
    op.drop_table('catalog_akas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_catalog_titles_ts_vector', table_name='catalog_titles', postgresql_using='gin')
    op.drop_index('ix_catalog_titles_start_year', table_name='catalog_titles')
    op.drop_index(op.f('ix_catalog_titles_imdb_tconst'), table_name='catalog_titles')
    op.drop_index(op.f('ix_catalog_titles_id'), table_name='catalog_titles')
    op.drop_index('ix_catalog_titles_genres', table_name='catalog_titles')
    op.drop_table('catalog_titles')
    op.drop_index(op.f('ix_catalog_people_imdb_nconst'), table_name='catalog_people')
    op.drop_index(op.f('ix_catalog_people_id'), table_name='catalog_people')
    op.drop_table('catalog_people')
    # ### end Alembic commands ###
