"""add_personal_logging_tables

Revision ID: f8650a768763
Revises: b27df8dbee4b
Create Date: 2026-02-04 06:55:56.830217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8650a768763'
down_revision: Union[str, Sequence[str], None] = 'b27df8dbee4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_movies')
    op.drop_table('movie_embeddings')
    op.drop_table('profile_taste')
    op.add_column('list_items', sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('list_items', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('list_items', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('uq_list_item_unique'), 'list_items', type_='unique')
    op.create_index(op.f('ix_list_items_id'), 'list_items', ['id'], unique=False)
    op.create_unique_constraint('uq_listitem_list_title', 'list_items', ['list_id', 'title_id'])
    op.create_foreign_key(None, 'list_items', 'catalog_titles', ['title_id'], ['id'])
    op.add_column('lists', sa.Column('list_type', sa.Enum('watchlist', 'favorites', 'rewatch', 'custom', name='listtype'), nullable=False))
    op.add_column('lists', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('lists', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('lists', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lists', 'name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.create_index(op.f('ix_lists_id'), 'lists', ['id'], unique=False)
    op.create_foreign_key(None, 'lists', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('lists', 'type')
    op.add_column('movie_flags', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('movie_flags', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movie_flags', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_movie_flags_id'), 'movie_flags', ['id'], unique=False)
    op.create_foreign_key(None, 'movie_flags', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie_flags', 'catalog_titles', ['title_id'], ['id'])
    op.alter_column('tags', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tags', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_unique_constraint('uq_tag_profile_name', 'tags', ['profile_id', 'name'])
    op.create_foreign_key(None, 'tags', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.alter_column('watch_tags', 'watch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watch_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('watch_tags', 'id')
    op.add_column('watches', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('watches', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('watches', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watches', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('watches', 'notes',
               existing_type=sa.VARCHAR(length=4096),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_watches_id'), 'watches', ['id'], unique=False)
    op.create_foreign_key(None, 'watches', 'catalog_titles', ['title_id'], ['id'])
    op.create_foreign_key(None, 'watches', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watches', type_='foreignkey')
    op.drop_constraint(None, 'watches', type_='foreignkey')
    op.drop_index(op.f('ix_watches_id'), table_name='watches')
    op.alter_column('watches', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=4096),
               existing_nullable=True)
    op.alter_column('watches', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watches', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('watches', 'updated_at')
    op.drop_column('watches', 'created_at')
    op.add_column('watch_tags', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('watch_tags', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('watch_tags', 'watch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint('uq_tag_profile_name', 'tags', type_='unique')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.alter_column('tags', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('tags', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'movie_flags', type_='foreignkey')
    op.drop_constraint(None, 'movie_flags', type_='foreignkey')
    op.drop_index(op.f('ix_movie_flags_id'), table_name='movie_flags')
    op.alter_column('movie_flags', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movie_flags', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('movie_flags', 'created_at')
    op.add_column('lists', sa.Column('type', postgresql.ENUM('watchlist', 'favorites', 'rewatch', 'custom', name='listtype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.drop_index(op.f('ix_lists_id'), table_name='lists')
    op.alter_column('lists', 'name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('lists', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('lists', 'updated_at')
    op.drop_column('lists', 'created_at')
    op.drop_column('lists', 'list_type')
    op.drop_constraint(None, 'list_items', type_='foreignkey')
    op.drop_constraint('uq_listitem_list_title', 'list_items', type_='unique')
    op.drop_index(op.f('ix_list_items_id'), table_name='list_items')
    op.create_unique_constraint(op.f('uq_list_item_unique'), 'list_items', ['list_id', 'title_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('list_items', 'title_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('list_items', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('list_items', 'added_at')
    op.create_table('profile_taste',
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('taste_vector', sa.VARCHAR(length=384), autoincrement=False, nullable=True),
    sa.Column('taste_summary_text', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('profile_id', 'model_id', name=op.f('profile_taste_pkey'))
    )
    op.create_table('movie_embeddings',
    sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('vector', sa.VARCHAR(length=384), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('title_id', 'model_id', name=op.f('movie_embeddings_pkey'))
    )
    op.create_table('onboarding_movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('onboarding_movies_pkey')),
    sa.UniqueConstraint('title_id', name=op.f('onboarding_movies_title_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
